security:
    enable_authenticator_manager: true

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    encoders:
        App\Entity\User:
            algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            form_login: ~
            entry_point: form_login
            provider: app_user_provider
            custom_authenticator: App\Security\LoginAuthenticator
            logout:
                path: logout
                # where to redirect after logout
                # target: app_any_route

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
